{% set name = "svg2png" %}
{% set version = "4.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/domenic/svg2png/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 55a0a8f7936d24d8e0b4e31f2c3ad11ea97a3daac1b8fbc12e745cf45bffaee0

build:
  number: 5

requirements:
  build:
    - nodejs  # [unix]
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

test:
  commands:
     - svg2png --help

about:
  home: https://github.com/domenic/svg2png
  license: MIT
  license_file: LICENSE.txt
  summary: 'SVG-to-PNG Converter Using PhantomJS'

extra:
  recipe-maintainers:
    - Dimitar-92
    - ArchB1aZe
    - xhochy
