{% set name = "svg2png" %}
{% set version = "4.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/domenic/svg2png/tarball/5997ae9452796f480c13506c32cb04d1dc38369e
  sha256: 6fa41166e7532592fb60cfb71e9e37e7eec1998136c06bc1b981d724bfd13ef7

build:
  number: 4
  script: npm install . && npm install -g

requirements:
  host:
    - nodejs
  run:
    - nodejs

test:
  commands:
     - npm list -g {{ name }}

about:
  home: https://github.com/domenic/svg2png
  license: MIT
  license_file: LICENSE.txt
  summary: 'SVG-to-PNG Converter Using PhantomJS'

extra:
  recipe-maintainers:
    - Dimitar-92
    - ArchB1aZe
