travis:
  secure:
    BINSTAR_TOKEN: lNSa51rUK8zpiuJn6u7g+6a7omIp5vZu9I3xIIcmvVNotrZkLtDbw8FBO8U1xoMgmSFt/x9uGxA1oIbr9ui9fq1zVhDibpS/OkZ3nQRxeaDGNIYIgjJ2EMEUCg/W87jiyVIDhDI08Fe+MjeeR+YnfxtPYCW618YEBNTciDB4xxf3dLM3onj8mySv3H5l78hrH9iAXLYxtXe8mGnSRcZo6XOQhH8F8B7TYpTFOhBjH0jyq/Mgoi3z1mPdOmAoNwJja8mhQGhrHmyIrzd93x36ehDXTjJf3+l6w/9Kv8h4Pa79Oq3lj32qBqXVBravFS6WKL9QNgTNtBXIuNbURNhm7AoyHChNEm96PSGd6dsk2sgELKImpAyQxKlTRWX78VerGvx8HZxrbf6ajiSE4/mPKH/T3RWXD0hKOb83wdPXixAiRqVAvLOu0RDGtenf5jz1QVrFpY2sDuK+KYAKXaGzQvZBkzzEJtnagPgF9qw1QYKAK5U/q0A6+ydUK7w9XDiELXIkImKVnaUcvn/z3PaKuj++lduhgnPEIZd9qMoy74aXbF6ZwRk2PetuV/pyNit07JZkHlyL9oCGVQC9+tg6jRIiMEW3WuE+tXflEjVMfefymdQNW05qVOXQ1LDIXlrtBodNF8og7WcsIzRLHaoBvgYz+3ZIqAeGtMdDh0pFso4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
