travis:
  secure:
    BINSTAR_TOKEN: jU2WzYN6dm8bcIbaqfOTb6kIvlPXW2tuKvMCe3cnvvXr/lyr+G47DpSzIdzE3RQyP43dvRyohxBwmq3J+Lf2GZ/GbjOb6GB2aBSVuRBxAzw8dT/2az0Ckh3BUuQ5guXpTDu09itR8JOLya36v/E+2bEdYYNkwRob2k1Z3tOGDJJ1WLk6Z1xDPzHM0uavMnPeVsIabBfWVe0ZOymQvfMdz6HAiHze8m2TL6kMDrDgHWoxwbEbuMtqkjjG5XZDNBQKU0g5bqUQdksrunWM5FV/o8XNTEsYlc5Dtw1Jd2gwInHcwealRKyrRjuku0cgP4T2ljIcDtzvvRRrXuCKtBNOqIG+iTBHcXQMEhqyUTXNWF/CUx+hm9XYNG002aYqlVAiKgVOAH3aXVXO0zZYVBU0lt3CVEq38f6qZ4VINJE6ehWfbhgAuCtZuDh29T82yyNoupsOl7aM8jXa4ZfrtXp6CXdnpCROvCVeSW4KzM1etShqDFcexW7zbhUkM8kysAoJLkw2WX56EvSa5LSmZxNl5euVL94ZcTqBeJ3H1GeNjaJawbVm4t9Yyzp1fzTneDVyJww1zLuJHC5TWIKbTNUsSMOhqA2sHL+F6vFoY3UXxFCNc4RUu2q5LOkr35Uu48Yj5z0obTQRBN4nVY3iNdfeCn3TuBxrpAZYCIXdA43SJQE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
