travis:
  secure:
    BINSTAR_TOKEN: MfY10QLo/AHpOtO8ShsiCgUD3tAVQpg7E26mvOSDZpAQn3sE6lUJGh2X1yNXGBe/ERpUleESb//p50l6hd8bV2Rb+sHn/gL0LgKfS1lRFxGzSYDOzRr5Ag0sRInF1x6WjT4zlQ+ZhDYCpl/av31o8MTb+6SSFdhpOBMshz0VSGn49aCpgu6atm7O8Vo2r8/lSG1P2mtGNg9QIjjqjiZAyvfEI9o+dsUC38LODzyrAuSoaV4AUjqvP9lRHzw8XgrJKPEbdAmbUKSmfg/hX8nPM/8ARntkvsUCymoRELqlz8OBqK5J9PXziR3/36e4zo2I9JaUp3CvZBAR2TBXA5Gp83IGd93AmXWOMC2hmIUPdxhea/I+UhGQR2UKISIPNeCHUpy9gqK2NPr9fJ9yrqiT5R98i0PYPuSoGqAoXZe2oHrI4/57XFbjc7fY708yWVsupUJ2nhL0cDq4ZFX5dOSNcq0OT0U4xB6JN4SPCUK8DJtL6D2PRkg/CzhDx6OySvk510jZJ1e4FIEfbFFGn+8KfBAzth/M5+Cmxr+e+a9IN5oBpGxJkQuVm2S8qsqgNi+7D6fj4NouP+9FdeFJ35Cjw6NwfbpBNS30iYr1+37EI34ByeBJktJHL0fDZlgRDNHbr61+5w00cFh8x+yY0bIWvQBF68Z2YvO6Gh1S2LYawU8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
